name: 'App CI'

on:
  workflow_dispatch:
  push:
    branches: [ 'main', 'Dev', 'Test' ]

jobs:
  Build:
    runs-on: [ windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Required: Sets up the AL environment variables
      - name: Initialize Workflow
        uses: microsoft/AL-Go-Actions/WorkflowInitialize@v8.3
        with:
          shell: powershell

      # Corrected Path: Pointing to the internal Compile-App folder
      - name: Build Business Central App
        uses: microsoft/AL-Go-Actions/Compile-App@v8.3
        with:
          shell: powershell
          project: './BCTrainingApp'

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BC-Package
          path: BCTrainingApp/*.app
