name: Pull Request Handler

on:
  pull_request_target:
    branches:
      - Test
      - Dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: powershell

permissions:
  contents: read
  actions:  read
  pull-requests: write

jobs:
  PullRequestHandler:
    runs-on: [ windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize the workflow
        id: init
        uses: microsoft/AL-Go-Actions/WorkflowInitialize@v8.3
        with:
          shell: powershell

      - name: Read settings
        id: ReadSettings
        uses: microsoft/AL-Go-Actions/ReadSettings@v8.3
        with:
          shell: powershell

      - name: Build
        uses: microsoft/AL-Go-Actions/RunPipeline@v8.3
        with:
          shell:        powershell
          settingsJson: ${{ steps.ReadSettings.outputs.SettingsJson }}
          secretsJson:  '{}'

      - name: Finalize the workflow
        if: always()
        uses: microsoft/AL-Go-Actions/WorkflowPostProcess@v8.3
        with:
          shell:              powershell
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
